version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./src:/app/src
    restart: always

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./setup/db_setup.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - ${DB_PORT}:5432
