#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE TABLE teams (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(60) NOT NULL,
    abbreviation         varchar(3) NOT NULL
  );

  CREATE TABLE ranking_types (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(60) NOT NULL
  );

  CREATE TABLE team_rankings (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "teamId" integer references teams(id) NOT NULL,
    "rankingType" integer references ranking_types(id) NOT NULL,
    rank integer NOT NULL,
    CONSTRAINT unique_team UNIQUE("teamId", "rankingType"),
    CONSTRAINT unique_rank UNIQUE(rank, "rankingType"),
    CONSTRAINT rank_range CHECK (rank > 0 AND rank < 33)
  );

EOSQL
