#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE TABLE teams (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(60) NOT NULL,
    abbreviation         varchar(3) NOT NULL
  );

  CREATE TYPE ranking_type AS ENUM ('Power Ranking',
    'Strength of Schedule',
    'OLine Ranking',
    'DLine Ranking',
    'Secondary Ranking'
  );
  CREATE TABLE team_rankings (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "teamId" integer references teams(id) NOT NULL,
    "rankingType" ranking_type NOT NULL,
    rank integer NOT NULL,
    CONSTRAINT unique_team UNIQUE("teamId", "rankingType"),
    CONSTRAINT unique_rank UNIQUE(rank, "rankingType"),
    CONSTRAINT rank_range CHECK (rank > 0 AND rank < 33)
  );

  CREATE TYPE position_type AS ENUM ('QB', 'RB', 'WR', 'TE', 'K');
  CREATE TABLE players (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "teamId" integer references teams(id) NOT NULL,
    name VARCHAR(100),
    position position_type NOT NULL,
    number integer NOT NULL
  );

  CREATE TABLE schedule (
    id    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    away integer references teams(id) NOT NULL,
    home integer references teams(id) NOT NULL,
    week integer NOT NULL,
    year integer NOT NULL,
    CONSTRAINT unique_home UNIQUE(home, week, year),
    CONSTRAINT unique_away UNIQUE(away, week, year),
    CONSTRAINT week_range CHECK (week > 0)
  );



EOSQL
